name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publishosx
      run: dotnet publish -r osx-x64 -p:PublishSingleFile=true --self-contained false
    - name: Publishwin10
      run: dotnet publish -r win-x64 -p:PublishSingleFile=true --self-contained false
